export const HashWorker = () =>
  new Worker("./hash.worker.ts", { type: "module" });
export const IPCWorker = () =>
  new Worker("./ipc.worker.ts", { type: "module" });
export const CompressWorker = () =>
  new Worker("./compress.worker.ts", { type: "module" });
export const CompressBinaryWorker = () =>
  new Worker("./compressBinary.worker.ts", { type: "module" });
export const DecompressBinaryWorker = () =>
  new Worker("./decompressBinary.worker.ts", { type: "module" });
export const ParseYamlWorker = () =>
  new Worker("./parseYaml.worker.ts", { type: "module" });
